### PR TITLE
Create personal details page

### PR DESCRIPTION
**Pull request by ssrome**
- Page where users will add their personal and contact details

personal-details-1
personal-details-2

- Postcode lookup version (without functionality)

personal-details-postcode-lookup

### CODE REVIEW

**Review by Joseaie — APPROVED** [review]
Looks good to me :)

**Comment by ssrome** [comment]
@Joseaie added an alternative page but can't do the actual lookup for this version

**Comment by Joseaie** [comment]
> @Joseaie added an alternative page but can't do the actual lookup for this version

You can add the alternative as a separate PR, even if it doesn't actually function?

**Comment by ssrome** [comment]
It's already been pushed to this branch

**Comment by Joseaie** [comment]
Ah, I see... you could place this commit (git cherry-pick) on a new branch, revert it from this branch and make a separate PR? Or if that's too much, could you add some screenshots of that too, so we can see it please?

**Review by Joseaie — COMMENTED** [review]
Look the same essentially 😂 but thanks for adding the extra screenshot! Feel free to merge :)

**Comment by ssrome** [comment]
There's less boxes. If I can figure it out then I'll add to it. Thanks

**Pull request merged**
